- id: '1553574763116'
  alias: Soldering Iron
  trigger:
  - entity_id: switch.soldering_iron
    for: 00:45:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: You left the Soldering Iron On
    service: notify.pushbullet
  - data:
      entity_id: switch.soldering_iron
    service: switch.turn_off
- id: '1553642010818'
  alias: Heater On
  trigger:
  - entity_id: switch.space_heater
    for: 00:45:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: The space heater is on still
    service: notify.pushbullet
  - data:
      message: The space heater is on still
    service: tts.google_say
- id: '1553720468993'
  alias: Play PS4
  trigger:
  - entity_id: input_select.activities
    from: Watch tv
    platform: state
    to: Play PS4
  condition: []
  action:
  - data:
      activity: Play PS4
    entity_id: remote.living_room
    service: remote.turn_on
- id: '1553720677019'
  alias: Watch TV
  trigger:
  - entity_id: input_select.activities
    from: Play PS4
    platform: state
    to: Watch TV
  condition: []
  action:
  - data:
      activity: Everything Ong
    entity_id: remote.living_room
    service: remote.turn_on
- id: '1553982380723'
  alias: Closet Dead
  trigger:
  - entity_id: binary_sensor.closet_door
    for: 00:08:00
    platform: state
    to: unavailable
  condition: []
  action:
  - data:
      message: closet is dead
    service: notify.pushbullet
- id: '1554014432125'
  alias: Bedroom Tv
  trigger:
  - at: 01:30:00
    platform: time
  - at: 03:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.0220036060019473a0e1
    service: switch.turn_off
- id: '1554073549721'
  alias: Basement LED's Off
  trigger:
  - entity_id: light.fastled_ws2811_light
    for: 00:10:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.fastled_ws2811_light
    service: light.turn_off
- id: '1554095124518'
  alias: Dining Room Off
  trigger:
  - at: '23:59'
    platform: time
  - at: 09:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.dining_room_lamp
    service: switch.turn_off
- id: '1554182653349'
  alias: Dining Room On
  trigger:
  - at: 06:45
    platform: time
  - at: '14:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.dining_room_lamp
    service: switch.turn_on
- id: '1554183365100'
  alias: Attic Offline
  trigger:
  - entity_id: binary_sensor.attic_door
    for: 00:00:40
    platform: state
    to: unavailable
  condition: []
  action:
  - data:
      message: The attic is offline
    service: tts.google_say
  - data:
      message: attic is offline
    service: notify.pushbullet
- id: '1557321447497'
  alias: Attic Open
  trigger:
  - entity_id: binary_sensor.attic_door
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.012005975ccf7f6a66fc
    service: light.turn_on
- id: '1557321532713'
  alias: Attic Closed
  trigger:
  - entity_id: binary_sensor.attic_door
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.012005975ccf7f6a66fc
    service: light.turn_off
- id: '1563738986709'
  alias: Box Fan Off
  trigger:
  - entity_id: switch.box_fan
    for: 00:40:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.box_fan
    service: switch.turn_off
  - data:
      message: I turned off the box fan
    service: notify.pushbullet
- id: '1566951638439'
  alias: Garage light on
  trigger:
  - entity_id: switch.garage_lock
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.30063068dc4f229bc7c4
    service: light.turn_on
- id: '1566952050592'
  alias: Garage light off
  trigger:
  - entity_id: switch.garage_lock
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068dc4f229bc7c4
    service: light.turn_off
- id: '1567359528915'
  alias: PC Locked
  trigger:
  - entity_id: script.pc_lock
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      icon: https://www.home-assistant.io/images/favicon-192x192.png
      url: http://fiservedpiha.ddns.net
    service: notify.dave_s_phone
- id: '1569978091148'
  alias: Basement Light On
  trigger:
  - entity_id: binary_sensor.basement_motion_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068c44f33aa2eb7
    service: light.turn_on
  - data:
      entity_id: light.38583387c44f3391e8cc
    service: light.turn_on
- id: '1570395151871'
  alias: Basement Light Off
  trigger:
  - entity_id: light.30063068c44f33aa2eb7
    for: 00:05:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068c44f33aa2eb7
    service: light.turn_off
  - data:
      entity_id: light.38583387c44f3391e8cc
    service: light.turn_off
- id: '1571172196813'
  alias: Closet Open
  description: ''
  trigger:
  - entity_id: binary_sensor.closet_door
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.garage_light
    service: light.turn_on
- id: '1571172289060'
  alias: Closet Closed
  description: ''
  trigger:
  - entity_id: binary_sensor.closet_door
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.garage_light
    service: light.turn_off
- id: '1571264178883'
  alias: Hallway On
  trigger:
  - at: '16:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.
    entity_id: switch.hallway_lamp
    service: switch.turn_on
- id: '1571264237268'
  alias: Hallway Off
  trigger:
  - at: 07:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.0120059360019471b780
    service: switch.turn_off
- id: '1575088938907'
  alias: Playroom window lights On
  description: ''
  trigger:
  - at: '17:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.0120059360019471b780
    service: switch.turn_on
- id: '1575089100843'
  alias: Playroom window lights off
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - entity_id: switch.0120059360019471b780
    service: switch.turn_off
- id: '1576504235174'
  alias: Garage Door Left open
  description: ''
  trigger:
  - entity_id: cover.garage_door_2
    for: 00:05:00
    from: closed
    platform: state
    to: open
  - entity_id: cover.garage_door_2
    for: 00:10:00
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: the garage door is
    service: notify.pushbullet
  - data:
      message: you left the garage door open
    service: tts.cloud_say
- id: '1577661047364'
  alias: Hallway Lamp On
  description: ''
  trigger:
  - at: '16:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.hallway_lamp
    service: switch.turn_on
- id: '1577661107082'
  alias: Hallway Lamp Off
  description: ''
  trigger:
  - at: 02:00
    platform: time
  condition: []
  action:
  - entity_id: switch.hallway_lamp
    service: switch.turn_off
