- id: '1553720468993'
  alias: Play PS4
  trigger:
  - entity_id: input_select.activities
    from: Watch tv
    platform: state
    to: Play PS4
  condition: []
  action:
  - data:
      activity: Play PS4
    entity_id: remote.living_room
    service: remote.turn_on
- id: '1553720677019'
  alias: Watch TV
  trigger:
  - entity_id: input_select.activities
    from: Play PS4
    platform: state
    to: Everything On
  condition: []
  action:
  - data:
      activity: Everything Ong
    entity_id: remote.living_room
    service: remote.turn_on
- id: '1554014432125'
  alias: Bedroom Tv
  trigger:
  - at: 04:00
    platform: time
  - at: 05:00
    platform: time
  - at: 06:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.0220036060019473a0e1
    service: switch.turn_off
- id: '1554073549721'
  alias: Basement LED's Off
  trigger:
  - entity_id: light.fastled_ws2811_light
    for: 00:10:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.fastled_ws2811_light
    service: light.turn_off
- id: '1554095124518'
  alias: Dining Room Off
  trigger:
  - at: '23:59'
    platform: time
  - at: 09:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.dining_room_lamp
    service: switch.turn_off
- id: '1554182653349'
  alias: Dining Room On
  trigger:
  - at: 06:45
    platform: time
  - at: '14:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.dining_room_lamp
    service: switch.turn_on
- id: '1554183365100'
  alias: Attic Offline
  trigger:
  - entity_id: binary_sensor.attic_door
    for: 00:00:40
    platform: state
    to: unavailable
  condition: []
  action:
  - data:
      message: The attic is offline
    service: tts.google_say
  - data:
      message: attic is offline
    service: notify.pushbullet
- id: '1557321447497'
  alias: Attic Open
  trigger:
  - entity_id: binary_sensor.attic_door
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.012005975ccf7f6a66fc
    service: light.turn_on
- id: '1557321532713'
  alias: Attic Closed
  trigger:
  - entity_id: binary_sensor.attic_door
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.012005975ccf7f6a66fc
    service: light.turn_off
- id: '1566951638439'
  alias: Garage light on
  trigger:
  - entity_id: switch.garage_lock
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.30063068dc4f229bc7c4
    service: light.turn_on
- id: '1566952050592'
  alias: Garage light off
  trigger:
  - entity_id: switch.garage_lock
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068dc4f229bc7c4
    service: light.turn_off
- id: '1567359528915'
  alias: PC Locked
  trigger:
  - entity_id: script.pc_lock
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      icon: https://www.home-assistant.io/images/favicon-192x192.png
      url: http://fiservedpiha.ddns.net
    service: notify.dave_s_phone
- id: '1569978091148'
  alias: 'Basement Front Left Light  On '
  trigger:
  - entity_id: binary_sensor.basement_motion_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068c44f33aa2eb7
    service: light.turn_on
- id: '1570395151871'
  alias: Basement Light Off
  trigger:
  - entity_id: light.30063068c44f33aa2eb7
    for: 00:05:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.30063068c44f33aa2eb7
    service: light.turn_off
  - data:
      entity_id: light.38583387c44f3391e8cc
    service: light.turn_off
- id: '1571172196813'
  alias: Closet Open
  description: ''
  trigger:
  - entity_id: binary_sensor.closet_door_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.garage_light
    service: light.turn_on
- id: '1571264178883'
  alias: Hallway On
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.
    entity_id: switch.hallway_lamp
    service: switch.turn_on
- id: '1575088938907'
  alias: Playroom Lamp On
  description: ''
  trigger:
  - at: '14:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.0120059360019471b780
    service: switch.turn_on
- id: '1575089100843'
  alias: Playroom Lamp Off
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - entity_id: switch.0120059360019471b780
    service: switch.turn_off
- id: '1576504235174'
  alias: Garage Door Left open
  description: ''
  trigger:
  - entity_id: cover.garage_door_2
    for: 00:05:00
    from: closed
    platform: state
    to: open
  - entity_id: cover.garage_door_2
    for: 00:10:00
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: the garage door is Open
    service: notify.pushbullet
  - data:
      message: you left the garage door open
    service: tts.google_translate_say
- id: '1577661047364'
  alias: Hallway Lamp On
  description: ''
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - entity_id: switch.hallway_lamp
    service: switch.turn_on
- id: '1577661107082'
  alias: Hallway Lamp Off
  description: ''
  trigger:
  - at: 02:00
    platform: time
  condition: []
  action:
  - entity_id: switch.hallway_lamp
    service: switch.turn_off
- id: '1586836292704'
  alias: Sump Pump Down
  description: ''
  trigger:
  - above: '0.0'
    below: '1.0'
    entity_id: sensor.sump_pump_power
    for: 00:00:30
    platform: numeric_state
  condition:
  - condition: state
    entity_id: weather.dark_sky
    state: rainy
  - condition: state
    entity_id: weather.dark_sky
    state: cloudy
  action:
  - data:
      message: check the sump pump
    service: notify.pushbullet
- id: '1587539980838'
  alias: Closet Closed
  description: ''
  trigger:
  - entity_id: binary_sensor.closet_door_2
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.garage_light
    service: light.turn_off
- id: '1588130455435'
  alias: 'Basement Back Left Light On '
  description: ''
  trigger:
  - entity_id: binary_sensor.basement_motion_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.38583387c44f3391e8cc
    service: light.turn_on
- id: '1588182695858'
  alias: GDACS
  description: ''
  trigger:
  - entity_id: sensor.gdacs_43_104581_79_034028
    from: ok
    platform: state
  condition: []
  action:
  - data:
      entity_id: media_player.googlehome0714
      message: the world is ending
    service: tts.google_translate_say
  - data:
      entity_id: media_player.family_room_display
      message: the world is ending
    service: tts.google_translate_say
  - data:
      entity_id: media_player.googlehome5385
      message: the world is ending
    service: tts.google_translate_say
- id: '1588223288721'
  alias: Color Ink Low
  description: ''
  trigger:
  - entity_id: sensor.hp_envy_4500_series_tri_color_ink
    platform: state
    to: '10'
  condition: []
  action:
  - data:
      message: color ink low
    service: notify.pushbullet
- id: '1588223433207'
  alias: Black Ink Low
  description: ''
  trigger:
  - entity_id: sensor.hp_envy_4500_series_black_ink
    platform: state
    to: '10'
  condition: []
  action:
  - data:
      message: black ink low
    service: notify.pushbullet
