# Loads default set of integrations. Do not remove.
default_config:
# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Customization file
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Example configuration.yaml entry
zeroconf:

# Example configuration.yaml entry
api:

# Example configuration.yaml entry
assist_pipeline:

# Example configuration.yaml entry
homeassistant_alerts:

# Example configuration.yaml entry
http:
##server_port: 8123
##cors_allowed_origins:
##    - https://google.com
##    - https://www.home-assistant.io
##  use_x_forwarded_for: true
##  trusted_proxies:
##    - 192.168.1.0/24
##    - 172.30.32.0/24
##    - 172.70.126.0/24
  ip_ban_enabled: false
##  login_attempts_threshold: 5

sensor:
  - platform: sonarr_upcoming_media 
    api_key: !secret_api  
    host: 192.168.1.10
    port: 8989 
    days: 7
    ssl: false
    max: 10
  - platform: plex_recently_added 
    token: !secret_token
    host: local.host
    port: 32400

mqtt:
  - sensor: 
      name: "Sump Pump Energy Today"
      state_topic: "tele/wattman2/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"

  - sensor:
      name: "Sump Pump Energy Total"
      state_topic: "tele/wattman2/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"

  - sensor:
      name: "Sump Pump Power"
      state_topic: "tele/wattman2/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"

  - sensor:
      name: "Sump Pump Voltage"
      state_topic: "tele/wattman2/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"

  - sensor:
      name: "Sump Pump Current"
      state_topic: "tele/wattman2/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
  
  - switch:
      name: "Sump Pump"  
      command_topic: "cmnd/wattman2/POWER" 
      state_topic: "stat/wattman2/POWER" 
      qos: 1
      payload_on: "ON" 
      payload_off: "OFF"   
      retain: "true"

  - switch:
      name: "Playroom Lamp"  
      command_topic: "cmnd/holiday-plug1/power" 
      state_topic: "stat/holiday-plug1/POWER" 
      qos: 1
      payload_on: "ON" 
      payload_off: "OFF"   
      retain: "true"

  - switch:
      name: "Dining Room Lamp"  
      command_topic: "cmnd/diningroomlamp/POWER" 
      state_topic: "stat/diningroomlamp/POWER" 
      qos: 1
      payload_on: "ON" 
      payload_off: "OFF"   
      retain: "true"

  - switch:
      name: "Hallway Lamp"  
      command_topic: "cmnd/hallway_lamp/power" 
      state_topic: "stat/hallway_lamp/POWER" 
      qos: 1
      payload_on: "ON" 
      payload_off: "OFF"   
      retain: "false"

  - switch:
      name: "Living Room Lamp"  
      command_topic: "cmnd/livingroomlamp/POWER" 
      state_topic: "stat/livingroomlamp/POWER" 
      qos: 1
      payload_on: "ON" 
      payload_off: "OFF"   
      retain: "true"

  - light:
      name: "Merkary_8"
      command_topic: "cmnd/mbulb8/POWER"
      state_topic: "stat/mbulb8/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "true"

  - light:
      name: "Bathroom_2" 
      command_topic: "cmnd/mbulb2/POWER"
      state_topic: "stat/mbulb2/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "true"

  - light:
      name: "Bathroom_1"
      command_topic: "cmnd/mbulb1/POWER"
      state_topic: "stat/mbulb1/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "true"

  - light:
      name: "Bathroom_3"
      command_topic: "cmnd/mbulb3/POWER"
      state_topic: "stat/mbulb3/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "true"
    
  - light: 
      name: "Merkary_4"
      command_topic: "cmnd/mbulb4/POWER"
      state_topic: "stat/mbulb4/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "false"

  - light: 
      name: "Merkary_5"
      command_topic: "cmnd/mbulb5/POWER"
      state_topic: "stat/mbulb5/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "false"
   
  - light:
      name: "Merkary_6"
      command_topic: "cmnd/mbulb6/POWER"
      state_topic: "stat/mbulb6/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "false"

  - light:
      name: "Basement Stairs"
      command_topic: "cmnd/mbulb7/POWER"
      state_topic: "stat/mbulb7/POWER"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      retain: "true"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  resources: !include resources.yaml
